### ISSUE TITLE
Create dev build and production build

### ISSUE THREAD

**Issue by brenoc** [vtex-apps/storefront-sdk#38]
Today, the SDK has only one Javascript file if all of its code. We want to improve the debuggability during development adding something like #30, but this comes with a cost, it increases the file size.

To serve this two purposes, small file size and help developers, we should provide a way to load two different builds of the SDK, one for developers, with all the debug messages, and other for production super slim.

Maybe we achieve this doing something like this in `layout.html`:
```
{% capture sdk %}storefront-sdk{% if user.roles.developer %}-dev{% endif %}.js@vtex.storefront-sdk{% endcapture %}
{% script sdk %}
```

Today the variable `user.roles.developer` is always `false`.

@brunoabreu @amoreira, can you make this variable work properly? Or maybe propose another solution, like checking the workspace?

**Comment by brunoabreu** [comment]
@brenoc, that was a side effect of the sandbox cookie removal, since developer mode was associated with it.

It's already fixed on our master branch and will be working properly in the next release.

**Comment by brenoc** [comment]
@brunoabreu great!
