### ISSUE TITLE
Remove lodash enterily

### ISSUE THREAD

**Issue by brenoc** [vtex-apps/storefront-sdk#39]
Just discovered https://github.com/danvk/source-map-explorer. It's a:

> Analyze and debug JavaScript code bloat through source maps.

> The source map explorer determines which file each byte in your minified JS came from. It shows you a treemap visualization to help you debug where all the code is coming from.

So I run it on the sdk bundle and the results are staggering:
![lodash](https://cloud.githubusercontent.com/assets/284515/11161406/f33a5990-8a62-11e5-98dd-b86dad236196.png)

**Comment by dfosco** [comment]
whoa! what does that mean for the SDK in terms of performance?

**Comment by brenoc** [comment]
A lot of bloat from lodash. Maybe we should use slimmer helper libraries or just implement the functions ourselves.

**Comment by tamorim** [comment]
The purpose of lodash-compat was to only put what we use, whats happening?

**Comment by tamorim** [comment]
And @brenoc maybe that's why the sourcemap on Closure Compiler got thinner... Dead Code Elimination?

**Comment by brenoc** [comment]
@tamorim Those functions have dependencies of other functions.

**Comment by brenoc** [comment]
@tamorim There's two output files:

- storefront-sdk-libs.js
- storefront-sdk.js

I only analyzed `storefront-sdk.js` that's where our code lives. Closure Compiler only reduced the file size of `storefront-sdk-libs.js`, it didn't change a thing about the second, remember?

**Comment by tamorim** [comment]
@brenoc It changed the size of the sourcemap too

**Comment by tamorim** [comment]
And hey, what about this? https://lodash.com/custom-builds
So we do a custom build with some handpicked ones?

**Comment by brenoc** [comment]
UOW, I found out. Wait for the commit!

**Comment by brenoc** [comment]
From this:
```
storefront-sdk-libs.js   259 kB       0  [emitted]  sdk-libs
    ./storefront-sdk.js   104 kB       1  [emitted]  .
./storefront-sdk.js.map  1.15 MB       1  [emitted]  .
```

To:
```
storefront-sdk-libs.js   259 kB       0  [emitted]  sdk-libs
    ./storefront-sdk.js  63.9 kB       1  [emitted]  .
./storefront-sdk.js.map   448 kB       1  [emitted]  .
```

**Comment by tamorim** [comment]
WHOA! :open_mouth:

**Comment by brenoc** [comment]
New source explorer:
![source](https://cloud.githubusercontent.com/assets/284515/11161552/34939eb6-8a67-11e5-92c9-51968e402e93.png)

**Comment by tamorim** [comment]
@brenoc Thought you would put *collection* in the mix too

**Comment by brenoc** [comment]
@tamorim What do you mean?

**Comment by brenoc** [comment]
@tamorim oh, yeah, we could stop using `each` for instance, but we don't have a cross browser `map` yet.

**Comment by tamorim** [comment]
@brenoc Yup, and there's runtime performance too! Although we don't operate on such large lists
